# Generated by Django 4.1.7 on 2023-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dentist_Assistant', '0004_alter_patient_gender_alter_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='Female', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married')], default='Married', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='progress',
            field=models.CharField(blank=True, choices=[('B', 'Beginning'), ('I', 'In Progress'), ('C', 'Completed')], default='In Progress', max_length=1, null=True),
        ),
    ]
