# Generated by Django 4.1.7 on 2023-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dentist_Assistant', '0005_alter_patient_gender_alter_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='progress',
            field=models.CharField(blank=True, choices=[('B', 'Beginning'), ('I', 'In Progress'), ('C', 'Completed')], default='B', max_length=1, null=True),
        ),
    ]
